/* Generated by Together */

#ifndef DRECT_H
#define DRECT_H
class DRect
{
public:
    DRect()
      {
        left = right = top = bottom = 0;
      }

    double left, right, top, bottom;
};
#endif //DRECT_H
